const DEFAULT_TEAMS=["Brett", "Jack", "Jackson", "John", "Josh", "Kyle", "Mike", "RJ", "Ryan", "Taft", "Tyler", "FNs"];
const KEY='ffDraftCenter_2026_v2';
const DEF={teams:DEFAULT_TEAMS,my:0,scoring:'PPR',starters:{QB:1,RB:2,WR:2,TE:1,FLEX:1,K:1,DST:1},bench:7,picks:[]};
let S=(()=>{try{return {...DEF,...JSON.parse(localStorage.getItem(KEY)||'{}'),starters:{...DEF.starters,...(JSON.parse(localStorage.getItem(KEY)||'{}').starters||{})}}}catch(e){return structuredClone(DEF)}})();
let pos='ALL';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function teamForPick(n){let r=Math.floor((n-1)/12)+1,i=(n-1)%12;return r%2?i:11-i}
function round(n){return Math.floor((n-1)/12)+1}
function drafted(){return new Set(S.picks.map(x=>x.name))}
function roster(t){return S.picks.filter(x=>x.team===t).map(x=>P.find(p=>p.name===x.name)).filter(Boolean)}
function mine(){return roster(S.my)}
function count(r,p){return r.filter(x=>x.pos===p).length}
function baseRank(p){if(Number.isFinite(p.fp))return p.fp;if(Number.isFinite(p.deepRank))return p.deepRank;return 9999}
function market(p){if(Number.isFinite(p.fp))return Math.max(1,p.fp+(p.marketGap||0));return baseRank(p)}
function scoringAdj(p){if(S.scoring==='PPR')return 0;if(S.scoring==='HALF')return p.pos==='RB'?-1:(['WR','TE'].includes(p.pos)?1:0);if(S.scoring==='STD')return p.pos==='RB'?-4:(p.pos==='WR'?3:p.pos==='TE'?3:0);return 0}
function composite(p){if(!Number.isFinite(p.fp))return baseRank(p);let vals=[[p.fp,.46],[market(p),.18]];if(p.espn)vals.push([p.espn,.36]);let w=vals.reduce((a,x)=>a+x[1],0),v=vals.reduce((a,x)=>a+x[0]*x[1],0)/w;return Math.max(1,v+scoringAdj(p)+(p.newsDelta||0))}
function nextMine(){for(let n=S.picks.length+1;n<S.picks.length+50;n++)if(teamForPick(n)===S.my)return n}
function needBonus(p){let r=mine(),h={QB:count(r,'QB'),RB:count(r,'RB'),WR:count(r,'WR'),TE:count(r,'TE'),K:count(r,'K'),DST:count(r,'DST')},s=S.starters,rd=round(S.picks.length+1);if(p.pos==='RB')return h.RB<s.RB?38:h.RB<s.RB+s.FLEX+2?14:-5;if(p.pos==='WR')return h.WR<s.WR?38:h.WR<s.WR+s.FLEX+3?16:-5;if(p.pos==='QB')return h.QB<s.QB?(rd<4?-10:rd<7?12:34):-50;if(p.pos==='TE')return h.TE<s.TE?(rd<4?-7:rd<7?11:32):-42;if(p.pos==='K')return rd<12?-80:(h.K<s.K?20:-50);if(p.pos==='DST')return rd<11?-75:(h.DST<s.DST?22:-50);return 0}
function rec(p){let n=nextMine(),m=market(p),urg=n&&m<n-4?13:0;return 1000-composite(p)*3+needBonus(p)+Math.max(-20,Math.min(20,(m-composite(p))*.8))+urg}
function avail(){let d=drafted();return P.filter(p=>!d.has(p.name))}
function renderHead(){let n=S.picks.length+1,t=teamForPick(n);$('pickN').textContent=n;$('roundN').textContent=round(n);$('onClock').textContent=S.teams[t];$('override').innerHTML='<option value="">Auto team</option>'+S.teams.map((x,i)=>`<option value="${i}">${esc(x)}</option>`).join('')}
function renderRows(){let q=$('search').value.toLowerCase(),nf=$('newsFilter').value,sort=$('sort').value;let a=avail().filter(p=>(pos==='ALL'||p.pos===pos)&&(!q||p.name.toLowerCase().includes(q)||p.team.toLowerCase().includes(q))&&(nf!=='news'||p.newsNote));a.sort((x,y)=>sort==='fp'?baseRank(x)-baseRank(y):sort==='espn'?(x.espn||baseRank(x))-(y.espn||baseRank(y)):sort==='market'?market(x)-market(y):sort==='composite'?composite(x)-composite(y):rec(y)-rec(x));$('availableN').textContent=avail().length;$('rows').innerHTML=a.map((p,i)=>`<tr><td><b>${i+1}</b><div class="meta">${Number.isFinite(p.fp)?Math.round(rec(p))+' pts':'deep pool'}</div></td><td><div class="playerline"><div class="name">${esc(p.name)}</div><button class="btn primary draft-inline" onclick="draftIndex(${P.indexOf(p)})">Draft</button></div><div class="meta">${p.team}${p.sleeperId?' • Sleeper':''}</div></td><td><span class="pos ${p.pos}">${p.pos}</span></td><td><b>${Number.isFinite(p.fp)?composite(p).toFixed(1):'Unranked'}</b></td><td>${Number.isFinite(p.fp)?p.fp:'—'}</td><td>${p.espn||'—'}</td><td>${Number.isFinite(p.fp)?market(p):'—'}</td><td>${p.newsNote?`<div class="news"><span class="tag">${esc(p.newsTag)}</span><br>${esc(p.newsNote)}</div>`:(p.sleeperId?'<span class="meta">Sleeper active pool</span>':'<span class="meta">—</span>')}</td></tr>`).join('')}
function draft(name){let n=S.picks.length+1,t=teamForPick(n);S.picks.push({pick:n,team:t,name});save();render()}
function draftToSelectedTeam(name){let n=S.picks.length+1,o=$('override').value,t=o===''?teamForPick(n):+o;S.picks.push({pick:n,team:t,name});$('override').value='';save();render()}
window.draft=draft;window.draftIndex=i=>draft(P[i].name);
function slots(){let r=mine(),used=new Set(),out=[],add=(label,p,n)=>{for(let k=0;k<n;k++){let i=r.findIndex((x,j)=>!used.has(j)&&x.pos===p);if(i>=0){used.add(i);out.push([label,r[i]])}else out.push([label,null])}};add('QB','QB',S.starters.QB);add('RB','RB',S.starters.RB);add('WR','WR',S.starters.WR);add('TE','TE',S.starters.TE);for(let k=0;k<S.starters.FLEX;k++){let i=r.findIndex((x,j)=>!used.has(j)&&['RB','WR','TE'].includes(x.pos));if(i>=0){used.add(i);out.push(['FLEX',r[i]])}else out.push(['FLEX',null])}add('K','K',S.starters.K);add('D/ST','DST',S.starters.DST);r.forEach((x,j)=>{if(!used.has(j))out.push(['BENCH',x])});while(out.filter(x=>x[0]==='BENCH').length<S.bench)out.push(['BENCH',null]);return out}
function renderSide(){let a=avail().sort((x,y)=>rec(y)-rec(x));$('recs').innerHTML=a.slice(0,5).map((p,i)=>`<div class="recommend"><span class="score">${Math.round(rec(p))}</span><b>#${i+1} ${esc(p.name)}</b><div class="meta">${p.pos} • ${p.team} • composite ${composite(p).toFixed(1)} • market ${market(p)}</div>${p.newsTag?`<div class="meta" style="color:#f2c96f">${esc(p.newsTag)}</div>`:''}</div>`).join('');$('mineName').textContent=S.teams[S.my];$('roster').innerHTML=slots().map(([s,p])=>`<div class="slot"><small>${s}</small><b>${p?esc(p.name):'<span class="meta">Empty</span>'}</b>${p?`<div class="meta">${p.pos} • ${p.team}</div>`:''}</div>`).join('');let n=nextMine(),best=a[0],r=mine();$('intel').innerHTML=`<div><b>Next pick:</b> ${n}</div><div style="margin-top:6px"><b>Top recommendation:</b> ${best?esc(best.name):'—'}</div><div style="margin-top:9px" class="meta">Current starters drafted: QB ${count(r,'QB')}/${S.starters.QB}, RB ${count(r,'RB')}/${S.starters.RB}, WR ${count(r,'WR')}/${S.starters.WR}, TE ${count(r,'TE')}/${S.starters.TE}. The score also penalizes early K/DST picks and reacts to roster need.</div>`}
function renderBoard(){let pm=new Map(S.picks.map(x=>[x.pick,x])),max=192,h='';for(let n=1;n<=max;n++){let x=pm.get(n),t=x?x.team:teamForPick(n),now=n===S.picks.length+1;h+=`<div class="pick ${now?'now':''}"><div class="pn">${n} • R${round(n)}</div><div class="pp">${x?esc(x.name):(now?'ON CLOCK':'—')}</div><div class="pt">${esc(S.teams[t])}</div></div>`}$('boardGrid').innerHTML=h}
function renderTeams(){$('teamsGrid').innerHTML=S.teams.map((t,i)=>{let r=roster(i);return `<div class="team ${i===S.my?'mine':''}"><h3>${esc(t)}${i===S.my?' <span style="color:#69dfa9">• YOUR TEAM</span>':''}</h3>${r.length?r.map(p=>`<div class="tp"><span>${esc(p.name)}</span><span class="meta">${p.pos}</span></div>`).join(''):'<span class="meta">No picks yet</span>'}</div>`}).join('')}
function renderSettings(){$('myTeam').innerHTML=S.teams.map((t,i)=>`<option value="${i}">${esc(t)}</option>`).join('');$('myTeam').value=S.my;$('scoring').value=S.scoring;for(let k of ['QB','RB','WR','TE','FLEX','K','DST'])$('s'+k).value=S.starters[k];$('bench').value=S.bench;$('teamOrder').value=S.teams.join(', ')}